### ISSUE TITLE
Small naming bug in `mousemove` event listener

### ISSUE THREAD

**Issue by biernacki** [drcmda/react-with-gesture#10]
In the current implementation there is a small bug regarding the `mousemove` event handler - `this.handleMouseMoveRaf` doesn't exist, it should be `this.handleMouseMove`

https://github.com/drcmda/react-with-gesture/blob/master/src/index.js#L41

**Comment by drcmda** [comment]
Ups, saw it, thanks - i'll take care of it after cleaning up the useGesture code duplication.

**Comment by biernacki** [comment]
@drcmda you're quick 👍
