### ISSUE TITLE
[BUG] Uncaught ReferenceError: initialstate is not defined in v2

### ISSUE THREAD

**Issue by biernacki** [drcmda/react-with-gesture#12]
On line [105](https://github.com/drcmda/react-with-gesture/blob/master/src/index.js#L105) and [108](https://github.com/drcmda/react-with-gesture/blob/master/src/index.js#L108) `initialstate` is lowercased which causes an `Uncaught ReferenceError: initialstate is not defined`.

**Comment by drcmda** [comment]
should be fixed now, thanks!
