### ISSUE TITLE
[Question] y assigned to pageX

### ISSUE THREAD

**Issue by mateeyow** [drcmda/react-with-gesture#4]
Just curious, is there a reason why you assigned `y` state to `pageX` and not `pageY`?

```js
const newProps = { ...this.state, x: pageX, y: pageX, xDelta: 0, yDelta: 0, xInitial: pageX, yInitial: pageY, xPrev: pageX, yPrev: pageY, down: true }
```

This instance is in both `handleMouseDown` and `handleMouseMove`

**Comment by drcmda** [comment]
Typo. Haven't used pageX/Y in an app with this libs before and didn't see it. Thanks for the PR!
