### ISSUE TITLE
Add example for triggering actions on swipe

### ISSUE THREAD

**Issue by sampl** [drcmda/react-with-gesture#8]
I'd love to know the best way to trigger an event based on a gesture.

For ex: let's say someone using [the demo](https://codesandbox.io/embed/jzn14k0ppy) drags the box to the right and releases it to "accept" that item. Where and how would you actually call an `acceptItem` function?

Happy to refile elsewhere if this isn't the right place. Thanks!

**Comment by sampl** [comment]
@monstersintokyo just what I needed--thank you so much!

**Comment by monstersintokyo** [comment]
@sampl you're welcome :-)

**Comment by tim-soft** [comment]
@drcmda how would this example work now that we only have the `onAction` callback? 

Including `onAction` means we can update component state based on events but the children of `<Gesture />` don't re-render.

Doing it like this isn't gonna work well
```jsx

updateState = () => this.setState({ ... });

<Gesture>
  {({ ... }) => {
      // Calling this.setState() from render() is bad...
      if (some gesture condition is met) this.updateState();

      return (
        <Spring>
            {...}
        </Spring>
      );
    }
  }
</Gesture>
```

**Comment by drcmda** [comment]
@tim-soft did something change? how did you do it before? i think otherwise in the class base api that needs to be componentDidUpdate that does the updateState().

**Comment by tim-soft** [comment]
In an older version, we could call setState() based on some gesture event like in https://codesandbox.io/embed/w0x1030lwk without interfering in the animation

```jsx
updateState = (props) => {
  this.setState({ ... });

  return props;
}

<Gesture onMove={this.updateState}>
  {({ ... }) => (
      <Spring>
          {...}
      </Spring>
    );
  }
</Gesture>
```

**Comment by drcmda** [comment]
the last bit i don't understand yet. if you're in onAction and you cause a setState, why wouldn't the spring animate?

**Comment by tim-soft** [comment]
Here's a codepen where I try to replicate  https://codesandbox.io/embed/3vv25z07j6

The top slider uses onAction to decide when to call setState()
The bottom slider tries to call setState() inside the render function --> obviously a noop

**Comment by drcmda** [comment]
I see. Could i interest you in adding these events back via PR?

now: https://github.com/react-spring/react-with-gesture/blob/master/index.js

then: https://github.com/react-spring/react-with-gesture/blob/5f243e0b1da7cf7e2c7ba5dc41f440993e8acca2/src/index.js

**Comment by tim-soft** [comment]
definitely 👍

**Comment by arpitprod** [comment]
`codesandbox` demo code not working. showing this error 

`ModuleNotFoundError
Could not find module in path: '@babel/runtime/helpers/builtin/es6/objectSpread' relative to '/node_modules/react-spring/dist/react-spring.es.js'`

How to solve ?

**Comment by dbismut** [comment]
@arpitprod This is an old issue. Swipe is documented in the documentation.
